### ISSUE TITLE
Dockerize codegen CLI

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/codegen#14]
Create a Dockerfile to build a Dockerized codegen cli. The resulting image should be as lightweight as possible. The flagd Dockerfile may be a good starting point.

https://github.com/open-feature/flagd/blob/main/flagd/build.Dockerfile

**Comment by thomaspoignant** [comment]
If you create the docker container from goreleaser it could be even lighter, since goreleaser is building the binary on their side.
Here an [example used for GO Feature Flag](https://github.com/thomaspoignant/go-feature-flag/blob/main/cmd/relayproxy/DockerfileGoreleaser).

**Comment by beeme1mr** [comment]
https://github.com/open-feature/codegen/pull/37
